version: '3'
services:
  ml:
    container_name: actions-ml-cicd_cpu_1
    image: hamelsmu/ml-cicd
    network_mode: "host"
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/data
    environment:
      - DASK_SCHEDULER
    command: tail -f /dev/null