name: ChatOps
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: machine-learning-apps/actions-chatops@master
        with:
          APP_PEM: ${{ secrets.APP_PEM }}
          APP_ID: ${{ secrets.APP_ID }}
          TRIGGER_PHRASE: "/run-full-test"
          INDICATOR_LABEL: "Full Test Pending"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
