name: Project Data to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'project/model_card.md'
      - 'project/data_dictionary.md'
      - 'project/model_events.csv'

jobs:
  copy-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false

      - name: Copy Repository Contents
        run: |
          chmod -R 777 docs/docs
          ./action_files/copy_files.sh

      - name: setup directories for Jekyll build
        run: |
          cd docs
          rm -rf _site
          sudo chmod -R 777 .

      - name: Jekyll build
        run: |
            docker run  -v /home/runner/work/actions-ml-cicd/actions-ml-cicd/docs:/workspace -w /workspace jekyll/jekyll jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.0.3
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: ./_site
          PUBLISH_BRANCH: gh-pages
