name: Project Data to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'project/model_card.md'
      - 'project/data_dictionary.md'
      - 'project/model_events.csv'

jobs:
  copy-build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Copy Repository Contents
        run: |
          chmod -R 777 docs/docs
          ./action_files/copy_files.sh
          ./action_files/push_to_repo.sh

      - name: setup directories for Jekyll build
        run: |
          rm -rf docs/_site
          sudo chmod -R 777 .

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v1

      - name: Jekyll build
        uses: docker://jekyll/jekyll
        with:
          args: jekyll build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.0.2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_DIR: ./docs/_site
