name: Google Cloud Function Deploy

on: deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: exelban/gcloud@master
      env:
        PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
        APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      with:
        args: functions deploy predict --runtime python37 --trigger-http --source=$GITHUB_WORKSPACE/src/deploy --set-env-vars WANDB_API_KEY=${{ secrets.WANDB_API_KEY }},WANDB_ENTITY=${{ secrets.WANDB_ENTITY }},WANDB_PROJECT=${{ secrets.WANDB_PROJECT }},WANDB_RUN_ID=${{ github.event.deployment.payload.wandb_run_id }}
    - run: |
        curl -d '{"state": "failure"}' -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/"$GITHUB_REPOSITORY"/deployments/"$DEPLOYMENT_ID"/statuses
      if: failure()
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEPLOYMENT_ID: ${{ github.event.deployment.id }}
    - run: |
        curl -d '{"state": "success"}' -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/"$GITHUB_REPOSITORY"/deployments/"$DEPLOYMENT_ID"/statuses
      if: success()
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DEPLOYMENT_ID: ${{ github.event.deployment.id }}
