name: ML Workflow Via Actions
on: push

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      
    - name: Publish Image to GPR
      uses: elgohr/Publish-Docker-Github-Action@master
      id: docker
      with:
        name: hamelsmu/ml-cicd
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: 'docker/Dockerfile'
        workdir: '.'
        cache: true

    - name: Show outputs of pervious step
      run: |
        echo "The name tag of the Docker Image is $VAR1"
      env:
        VAR1: ${{ steps.docker.outputs.tag }}        
