name: ML Workflow Via Actions
on: push

jobs:
  test-run:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      
    - name: Publish Image to GPR
      uses: elgohr/Publish-Docker-Github-Action@master
      id: docker
      with:
        name: hamelsmu/ml-cicd
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: docker.pkg.github.com
        dockerfile: 'docker/Dockerfile'
        workdir: '.'
        cache: true
        
