name: ML Workflow Via Actions
on:
  pull_request:
    types:
      - labeled

jobs:
  validate_run:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repo Files
      uses: actions/checkout@master
      
    - name: Validate Payload
      id: validate
      run: python gke-argo-action/validate_payload.py
      env:
        TRIGGER_LABEL_NAME: 'run/model-ci' 
        
        
