name: ML Workflow Via Actions
on: push

jobs:
  build-cpu-image:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      
    - name: Publish CPU Image to DockerHub
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        BASE_NAME="$USERNAME/ml-cicd"
        IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
        docker pull $BASE_NAME || true
        docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f docker/Dockerfile .
        docker push $IMAGE_NAME
        docker push $BASE_NAME
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   

  build-gpu-image:
    runs-on: ubuntu-latest
    steps:

    - name: Copy Repository Contents
      uses: actions/checkout@master
      
    - name: Publish GPU Image to DockerHub
      run: |
        cd $GITHUB_WORKSPACE
        echo ${PASSWORD} | docker login -u $USERNAME --password-stdin
        BASE_NAME="$USERNAME/ml-cicd-gpu"
        IMAGE_NAME="$BASE_NAME:$GITHUB_SHA"
        docker pull $BASE_NAME || true
        docker build --cache-from $BASE_NAME -t $IMAGE_NAME -t $BASE_NAME -f docker/Dockerfile .
        docker push $IMAGE_NAME
        docker push $BASE_NAME
      env:
        USERNAME: ${{ secrets.DOCKER_USERNAME }}
        PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  
  submit-argo-workflow:
    needs: [build-cpu-image, build-gpu-image]
    runs-on: ubuntu-latest
    steps: 
       - name: Copy Repo Files
         uses: actions/checkout@master

       - name: Submit Argo Deployment
         id: argo
         uses: machine-learning-apps/gke-argo@master
         with:
           ARGO_URL: ${{ secrets.ARGO_URI }}
           APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
           PROJECT_ID: ${{ secrets.GCLOUD_PROJECT_ID }}
           LOCATION_ZONE: "us-west1-a"
           CLUSTER_NAME: "github-actions-demo"
           WORKFLOW_YAML_PATH: argo/workflow.yaml # the argo workflow file relative to the repo's root.
           PARAMETER_FILE_PATH: argo/params.yml # optional parameter file.  This can be built dynamically inside the action or appended to from an existing file in the repo.
        
      



