name: Convert Notebooks To Docs
on:
  push:
    branches:
      - master
    paths:
      - 'notebooks/*.ipynb'

jobs:
  convert-notebook:
    if: contains(join(github.event.commits.*.message), '/sync')
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - uses: fastai/fastpages@master
      with:
        BOOL_SAVE_MARKDOWN: true
        SSH_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        FORMAT: 'notebook'

    - name: setup directories for Jekyll build
      run: |
        cd docs
        rm -rf _site
        sudo chmod -R 777 .
        
    - name: Jekyll build
      run: |
          docker run  -v /home/runner/work/actions-ml-cicd/actions-ml-cicd/docs:/workspace -w /workspace jekyll/jekyll jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_DIR: ./docs/_site
        PUBLISH_BRANCH: gh-pages
