name: Get token for prototyping
on: issue_comment

jobs:
  test:
    name: see-token
    runs-on: ubuntu-latest

    steps:
    - name: Write token
      run: | 
        echo $GITHUB_TOKEN > tok.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: token
        path: tok.txt
