name: Receive Repository Dispatch Payload
on: repository_dispatch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
    
    - name: handle repo dispatch payload
      id: rd
      run: |
        python3 action_files/repo_dispatch_handler.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Get Runs Using SHA
      uses: machine-learning-apps/wandb-action@master
      id: wandb
      with:
        PROJECT_NAME: ${{ format('{0}/{1}', secrets.WANDB_ENTITY, secrets.WANDB_PROJECT) }}
        FILTER_GITHUB_SHA: "0c8524ebb794c907446fc97a5fd18f5e4837e242"
        BASELINE_TAGS: "['baseline', 'reference']"
        DISPLAY_METRICS: "['accuracy', 'loss', 'val_accuracy', 'val_loss', ]"
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
        DEBUG: 'true'

    - name: Upload csv
      if: steps.wandb.outputs.BOOL_COMPLETE == 'true'
      uses: actions/upload-artifact@v1
      with:
        name: wandb_report
        path: wandb_report.csv
