name: See Repository Dispatch Payload
on: repository_dispatch

jobs:
  test:
    name: see-output
    runs-on: ubuntu-latest

    steps:
    - name: Write payload
      run: cat $GITHUB_EVENT_PATH > payload.json
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: payload
        path: payload.json

    - name: Copy Repository Contents
      uses: actions/checkout@master
    
    - name: handle repo dispatch payload
      run: |
        cd $GITHUB_WORKSPACE
        python3 action_files/label_app.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
