name: See Repository Dispatch Payload
on: repository_dispatch

jobs:
  test:
    name: see-output
    runs-on: ubuntu-latest

    steps:
    - name: Write payload
      run: cat $GITHUB_EVENT_PATH > payload.json
    - name: Upload payload
      uses: actions/upload-artifact@v1
      with:
        name: payload
        path: payload.json