name: Test
on: push

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: setup directories for Jekyll build
      run: |
        rm -rf docs/_site
        sudo chmod -R 777 docs

    - name: Jekyll build
      run: |
          docker run  -v /home/runner/work/actions-ml-cicd/actions-ml-cicd/docs:/workspace -w /workspace jekyll/jekyll jekyll build

    - name:  See files
      run: ls docs

    # only deploy upon a push to master
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      if: github.event_name == 'push'
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/_site
