name: test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: see if works
      run: | 
       sudo apt install python3-pip
       pip3 install github3.py jwt requests cryptography