name: pip install
on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: pip
      run: |
        sudo apt-get install python3-setuptools
        pip3 install wheel pandas tabulate
